server:
  port: 9527

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    #表示是否将自己注册进EurekaServer，默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh #payment_routh 路由的ID，没有固定规则但是要求唯一，建议配合服务名
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/get/** #断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_routh2 路由的ID，没有固定规则但是要求唯一，建议配合服务名
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/** #断言，路径相匹配的进行路由
            #- After=2021-06-18T16:58:39.293+08:00[Asia/Shanghai]  #在这个时间后可以访问该接口
            #- Before=2021-06-18T16:58:39.293+08:00[Asia/Shanghai]  #在这个时间前可以访问该接口
            #- Between=2021-06-18T17:00:00.000+08:00[Asia/Shanghai],2021-06-18T17:30:00.000+08:00[Asia/Shanghai] #在这个时间段之间，可以访问该接口
            #- Cookie=username,sunziren #cookie限制，表示cookie中必须有属性名username、值为sunziren的cookie，才能放行。
            #- Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性并且值为整数的正则表达式