server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

#设置openfeign客户端默认超时时间(openfeign内部集成了ribbon)
ribbon:
  #建立连接的超时时间
  ConnectTimeout: 5000
  #连接建立后，读取数据的超时时间
  ReadTimeout: 5000

feign:
  hystrix:
    enabled: true
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 10000